orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  build1:
    working_directory: /tmp
    docker:
      - image: docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker image ls
      - run: docker volume ls
      - run: docker run --mount source=datastore,destination=/mnt/volume debian:bullseye-slim dd if=/dev/zero of=/mnt/volume/zero bs=32M count=32
      - run: docker volume ls
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  app-tests:
    jobs:
      - node/test:
          version: 13.11.0
