orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  build:
    docker:
      - image: docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker image ls
      - run: docker volume ls
      - run: docker run --mount source=datastore,destination=/mnt/volume debian:bullseye-slim dd if=/dev/zero of=/mnt/volume/zero bs=32M count=32
      - run: docker volume ls

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 13.11.0
      - node/test:
          version: 12.16.0
      - node/test:
          version: 10.19.0

  app-tests:
    jobs:
      - build
  store_test_results:
    path: test-results
