orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  - node/test:
  build1:
    working_directory: /tmp
    docker:
      - image: docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker image ls
      - run: docker volume ls
      - run: docker run --mount source=datastore,destination=/mnt/volume debian:bullseye-slim dd if=/dev/zero of=/mnt/volume/zero bs=32M count=32
      - run: docker volume ls
      - store_test_results:
          path: test

workflows:
  app-tests:
    jobs:
      - build1
      
